training_p.set=./dataset/beibei/train.txt
training_c.set=./dataset/beibei/cart.txt
training_v.set=./dataset/beibei/pv.txt
type_num.set=./dataset/beibei/type_num.txt
test.set=./dataset/beibei/test.txt

model.name=TBSCCMR
model.type=multi_behavior
item.ranking=-topN 10

embbedding.size=64

num.max.epoch=200
batch_size=2048

r-adjNorm=0.5
learnRate=0.001
reg.lambda=0.001

dataset=Beibei
num=1
user_num=21716
item_num=7977

TBSCCMR=-n_layer 2 -l* 2 -lambda 0.1 -eps 0.1 -t 0.1
output.setup=-dir ./results/
